#!/usr/bin/env bash

bin=`dirname "$0"`
bin=`cd "$bin"; pwd`

if [ -n "${JAVA_HOME}" ]; then
    RUNNER="${JAVA_HOME}/bin/java"
else
    if [ `command -v java` ]; then
        RUNNER="java"
    else
        echo "JAVA_HOME is not set" >&2
        exit 1
    fi
fi

exec "$RUNNER" -cp  ./target/version-maven-plugin-1.0.3-SNAPSHOT.jar com.github.caofangkun.VersionInfo

